### PR TITLE
Feature 5959

### PR DESCRIPTION
**Pull request by delsborg**
Enhancements to people page.
Cleaned out old DCO items
Removed organizations and mostSpecificType
Added taughtCourse and hasHonor facets
Added courses and honors details to card
Added weblinks and social icons
Moved email to be an icon
Added picture thumbnail placeholder

Included request by Michelle that international activities come after Courses and Honors.

### CODE REVIEW

**Comment by aviggio** [comment]
Any updates on replacing the help page at top of page with a Help button/link and possibly "popup" help content to avoid taking up that key real estate? OK to tackle that as a separate release – just checking.

**Comment by delsborg** [comment]
HI Alex, I didn't work on that yet. 
I could setup a help button with on hover text, similar to what I did with the researchOverview button .
I can anchor a button on the right side and place it under the search bar. Then have the help text pop out to the left on hover. Any thoughts or opinions on what you want so I can incorporate that prior to starting?

**Comment by vancehoward** [comment]
In general, the new card layout looks **much** better than the current layout. Much easier to scan.

A couple questions on the changes mentioned: What is DCO? What is mostSpecificType?

Some details that caught my eye in the layout:

1. The LinkedIn icon doesn't feel right. It doesn't have curved edges. See here https://www.linkedin.com/in/e-scott-adler-7481216/
2. Each icon generates what looks like a hyperlink line underneath on hover. This seems unneeded.
3. Was there an intent to add tooltips on hover? Not seeing them.
4. The ORCID icon has a white background, which looks a little strange when you hover in the card. Perhaps a transparent background?
5. The ...more link seems a little off-kilter to me. The CU Boulder search results use just an ellipsis. See https://www.colorado.edu/search?cse=web+style+guide&op=Search Also, the ...more button on the profile page and elsewhere does a JavaScript show action or re-renders the page with more information shown in the same spot. The ...more link on the card takes the user to the faculty member detail page. These seem like different behaviors. The ...more links on the card also do not take the user to the anchor on the detail page. For instance, when I click on more for courses, I expect to be taken to courses, not just the top of the faculty member detail page. Perhaps the >> link should be used, since we're going to a different page? Seems like a consistent user experience supports more confidence in an application.
6. Clicking on the card photo (or placeholder) does not take the user to the faculty detail page. I expected that it would.
7. As I mentioned earlier, displaying the course numbers seems pretty useless to most people, who are not going to know which course numbers belong to which courses. Could a more useful alternative be to display the most recently taught course names, separated by semicolons, with links to details? The Elements Discovery module seems to provide a list of courses taught that is easy to scan https://faculty.utk.edu/Raymond.Bentley/teaching
8. The twitter logo seems cropped too tightly and doesn't seem to conform to twitter guidelines https://about.twitter.com/en_us/company/brand-resources.html

**Comment by delsborg** [comment]
Vance
DCO is Deep Carbon Observatory - they had identifiers in the code which we don't use, so I removed the chaf.
mostSpecificType should be an indicator that displays something like Academic Rank. This currently doesn't accurately represent our people in Experts, so I removed the display until this can be resolved.
Regarding other points.
We want to keep in mind that this codebase is most likely short lived and hopefully will be expired mid 2020.
Icon look and feel in general, Alex and I already paired on this a little already. It all takes time so if Alex wants me to spend more time tweaking the icons I can. It would be in lue of other tasks then.
Not sure what you mean by item 2. Do you mean the hyperlink in the bottom status bar of the browser? If so I didn't do anything to enable that. It does indicate where someone would go.
3. Yes, on hover is a bit of a pain with the templating engine. I time boxed a few hours on it and didn't get it to work properly. I can spend more time on that if directed.
4. You bring up 2 items with the more button
  a. ellipses  -- Alex and I paired on this solution. I'll spend more time on this if directed
  b. target link - proved to be difficult to pass the offset of the page and modify the target URL in the template. At least in the hour I spent on it. I could do more in javascript, but that will take more time.
6. Link on photo should be simple. I'll add that.
7. Course Subject+number - I'm not sure where you got your assesment that it's useless to most people, but the link is the shortSubject+Number and it does take them to the course detail currently. The option of most recently taught course names will involved more code and time. Recommend this be differed to the new codebase because the developers are discussing this type of option.
8. twitter icon tweak - just pulled this from font awesome. More time required to determine if this can be adjusted.

Also want to note that Michelle did approve this and Seth gave an initial OK.

**Comment by delsborg** [comment]
Hi Vance
We're pairing on this now.
We're settled on the more link text.
We did send people to the anchor as you suggested.

Courses - Matt and Alex are highlighting that by having courses now, we at least give more attention and leveling the playing field between faculty who teach more vs. faculty who just do research. The same goes for honors.

**Comment by delsborg** [comment]
Added on hover for icons

**Comment by delsborg** [comment]
removed underlines from highlighted  weblinks <a>

**Comment by delsborg** [comment]
Requested changes made along with Internet Explorer fix for sort.
Merging now.

**Pull request merged**
